#pragma once

enum MG1ItemIndex : uint8_t
{
    MG1_ITEM_INDEX_CIGARETTES = 0,
    MG1_ITEM_INDEX_FLASHLIGHT = 1,
    MG1_ITEM_INDEX_OXYGEN_CYLINDER = 2,
    MG1_ITEM_INDEX_RATIONS = 3,
    MG1_ITEM_INDEX_COMPASS = 4,
    MG1_ITEM_INDEX_BINOCULARS = 5,
    MG1_ITEM_INDEX_BOMB_BLAST_SUIT = 6,
    MG1_ITEM_INDEX_CARDBOARD_BOX = 7,
    MG1_ITEM_INDEX_INFRARED_GOGGLES = 8,
    MG1_ITEM_INDEX_TRANSMITTER = 9,
    MG1_ITEM_INDEX_ENEMY_UNIFORM = 10,
    MG1_ITEM_INDEX_ANTENNA = 11,
    MG1_ITEM_INDEX_MINE_DETECTOR = 12,
    MG1_ITEM_INDEX_PARACHUTE = 13,
    MG1_ITEM_INDEX_GAS_MASK = 14,
    MG1_ITEM_INDEX_ANTIDOTE = 15,
    MG1_ITEM_INDEX_CARD_1 = 16,
    MG1_ITEM_INDEX_AMMO = 17,
    MG1_ITEM_INDEX_MINE = 18,
    MG1_ITEM_INDEX_PLASTIC_EXPLOSIVE = 19,
    MG1_ITEM_INDEX_RC_MISSILE = 20,
    MG1_ITEM_INDEX_HANDGUN = 21,
    MG1_ITEM_INDEX_SUBMACHINE_GUN = 22,
    MG1_ITEM_INDEX_ROCKET_LAUNCHER = 23,
    MG1_ITEM_INDEX_GRENADE_LAUNCHER = 24,
    MG1_ITEM_INDEX_SUPPRESSOR = 25,
    MG1_ITEM_INDEX_EQUIPMENT_RECOVERY = 26,
    MG1_ITEM_INDEX_BANDANA = 27,
    MG1_ITEM_INDEX_BODY_ARMOR = 28,
    MG1_ITEM_INDEX_CARD_2 = 29,
    MG1_ITEM_INDEX_CARD_3 = 30,
    MG1_ITEM_INDEX_CARD_4 = 31,
    MG1_ITEM_INDEX_CARD_5 = 32,
    MG1_ITEM_INDEX_CARD_6 = 33,
    MG1_ITEM_INDEX_CARD_7 = 34,
    MG1_ITEM_INDEX_CARD_8 = 35,

    MG1_ITEM_INDEX_MAX_CARD_LEVEL = 8,
};

enum MG1Flag : uint8_t
{
    MG1_FLAG_EQUIPMENT_TAKEN = 129,   // snake's captured, blocks equipment screens & door access
};

enum MG1Stage : uint8_t
{
    MG1_STAGE_START_AREA = 0,
    MG1_STAGE_BUILDING_1_1F = 1,
    MG1_STAGE_BUILDING_1_2F = 2,
    MG1_STAGE_BUILDING_1_3F = 3,
    MG1_STAGE_BUILDING_1_B1 = 4,
    MG1_STAGE_DESERT_1 = 5,
    MG1_STAGE_BUILDING_1_ELEVATOR_HUB = 6,
    MG1_STAGE_BUILDING_1_ROOF_COURTYARD = 7,
    MG1_STAGE_BUILDING_2_1F = 8,
    MG1_STAGE_BUILDING_2_2F = 9,
    MG1_STAGE_BUILDING_2_B1 = 10,
    MG1_STAGE_DESERT_2 = 11,
    MG1_STAGE_BUILDING_2_ELEVATOR_HUB = 12,
    MG1_STAGE_BUILDING_2_ROOF = 13,
    MG1_STAGE_BUILDING_3_1F = 14,
    MG1_STAGE_BUILDING_3_BASEMENT = 15,
    MG1_STAGE_BUILDING_3_ELEVATOR_HUB = 16,
    MG1_STAGE_ESCAPE_ROUTE = 17,
};

enum MG1Scene : uint8_t
{
    MG1_SCENE_GAMEPLAY = 0x9,
    MG1_SCENE_TITLE_MENU = 0xA,
    MG1_SCENE_TRANSCEIVER = 0xF,
    MG1_SCENE_MESSAGE_WINDOW = 0x10,
    MG1_SCENE_ENDING = 0x15,
    MG1_SCENE_RESULTS = 0x16,
};

enum MG1AlertPhase : uint8_t
{
    MG1_ALERT_PHASE_NONE = 0,
    MG1_ALERT_PHASE_ALERT = 1,
    MG1_ALERT_PHASE_REINFORCEMENTS = 2,
};
