#pragma once

enum MG2PortraitFrame : uint8_t
{
    MG2_PORTRAIT_BIG_BOSS = 0,
    MG2_PORTRAIT_GRAY_FOX = 1,
    MG2_PORTRAIT_GRAY_FOX_DAMAGED = 2,
    MG2_PORTRAIT_HOLLY = 3,
    MG2_PORTRAIT_KASLER = 4,
    MG2_PORTRAIT_MARV = 5,
    MG2_PORTRAIT_CAMPBELL = 6,
    MG2_PORTRAIT_MADNAR = 7,
    MG2_PORTRAIT_MASTER_MILLER = 8,
    MG2_PORTRAIT_GUSTAVA_EYES_OPEN = 9,
    MG2_PORTRAIT_GUSTAVA_EYES_CLOSED = 10,
    MG2_PORTRAIT_JACOBSEN = 11,
    MG2_PORTRAIT_SNAKE = 12,
    MG2_PORTRAIT_SNAKE_SMOKING = 13,
    MG2_PORTRAIT_GUSTAVA_TRANSLATING = 14,
    MG2_PORTRAIT_NONE = 15,
};

enum MG2Scene : uint8_t
{
    MG2_SCENE_GAMEPLAY = 18,
    MG2_SCENE_RESULTS = 25,
};

enum MG2AlertMode : uint8_t
{
    MG2_ALERT_MODE_NORMAL = 0,
    MG2_ALERT_MODE_COUNTDOWN = 1,
    MG2_ALERT_MODE_ALERT = 2,
};
